server:
  port: 55
  contextPath: "/"
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/idm
    username: postgres
    password: postgres
    generate-ddl: false
  jpa:
    show-sql: true
    hibernate.ddl-auto: validate
  mail:
    host: smtp.yandex.ru
    username: user.game.access
    password: 390PEydq738
    port: 465
    protocol: smtp